{{- if .Values.models.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "local-ai.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "local-ai.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.models.persistence.annotations }}
    {{- toYaml .Values.models.persistence.annotations | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.models.persistence.storageClass }}
  storageClassName: {{ .Values.models.persistence.storageClass }}
  {{- end }}
  accessModes:
  {{- range .Values.models.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.models.persistence.size | quote }}
{{- end }}
